tifoon:
  scanner:
    active: true # false -> dry-run mode
    toolName: nmap # nmap
  commandExecutor: process # docker, process
  saveFormat: yaml # json, yaml
  scanRateSeconds: 30 # scan rate (in seconds)
  onlySaveReportOnChange: true
  dynamicBaselineMode: false # dynamically create a new baseline when a change is detected (be careful!)
  useInitialScanAsBaseline: false # true when seeding/boot-strapping new install, normally false
  baselineFilename: scans/port_scanner_report_20170307_170306.yml

logging:
  file: tifoon.log
  level:
    org.springframework: WARN
    org.javers: WARN
    org.polyjdbc: WARN
    org.hibernate: WARN
    com.elixlogic: INFO
