tifoon:
    scanRateSeconds: 10
    onlySaveReportOnChange: true
    useInitialScanAsBaseline: false
    dynamicBaselineMode: false
    baselineFilename: scans/port_scanner_report_20170305_225722.json

logging:
    level:
        org.springframework: WARN
        org.javers: WARN
        org.polyjdbc: WARN
        org.hibernate: WARN
        com.elixlogic: INFO
