tifoon:
    scanRateSeconds: 10
    onlySaveReportOnChange: true
    useInitialScanAsBaseline: false
    baselineFilename: scans/port_scanner_report_20170304_220841.json

spring:
    main:
        banner-mode: "off"

logging:
    level:
        org.springframework: WARN
        org.javers: WARN
        org.polyjdbc: WARN
        org.hibernate: WARN
        com.elixlogic: INFO
